[[pages]]
path = "./pages/1_introducao.py"
name = "Tech Challenge - Fase 4"
icon = "ğŸ–¥ï¸"

[[pages]]
path = "./pages/2_eda.py"
name = "ExploraÃ§Ã£o e Insights"
icon = "ğŸ“ˆ"

[[pages]]
path = "./pages/3_previsao.py"
name = "PrevisÃ£o"
icon = "âš™ï¸"

[[pages]]
path = "./pages/4_conclusao.py"
name = "ConclusÃ£o"
icon = "ğŸ¯"

